### ISSUE TITLE
呃 ，我又来这了，还是simple-module的bug

### ISSUE THREAD

**Issue by cy20006** [mycolorway/simditor-mention#10]
@farthinker 如题。。
![image](https://cloud.githubusercontent.com/assets/3981024/7410925/ef18cc9a-ef65-11e4-9bcd-7e68ad040103.png)

**Comment by cy20006** [comment]
@farthinker npm上的版本还是2.0.2，代码没变额。。

**Comment by farthinker** [comment]
发布v2.0.3了

**Comment by cy20006** [comment]
@farthinker 离成功只差一步！ package.json里面没有dependencies: simplemodule  
![](https://cloud.githubusercontent.com/assets/3981024/7410925/ef18cc9a-ef65-11e4-9bcd-7e68ad040103.png)

**Comment by farthinker** [comment]
修复了，增加了对simditor的依赖

**Comment by cy20006** [comment]
@farthinker 不行啊，还是提示缺少simplemodule

**Comment by farthinker** [comment]
simditor不是依赖simplemodule的吗？npm不能处理这种依赖？

**Comment by cy20006** [comment]
因为这个插件单独require了simplemodel,我的项目中没有单独装simplemodel，所以找不到

**Comment by farthinker** [comment]
这……npm不能重新发布版本好麻烦……
