### ISSUE TITLE
行间距的扩展问题

### ISSUE THREAD

**Issue by hellodajun** [mycolorway/simditor-mention#15]
目前simditor挺好用，就是缺少行间距的扩展，这个也挺常用的

**Comment by hellodajun** [comment]
会增加此功能嘛

**Comment by farthinker** [comment]
行间距扩展的具体需求是什么呢？

现在直接按回车是段落换行，行间距比较大，shift回车时段落内换行，行间距比较小，你可以试试

**Comment by hellodajun** [comment]
感谢楼主的回复，您所说的两种行间距的方式我试用了，shift回车的还是在一个段落P标签中编辑的加了一个br；直接回车是又新增了一个P标签，每个P标签margin-botton是15px，咱们这个行间距是固定的。我所说的是类似百度编辑器里的那种有个插件是可以选择行间距的，跟word中的也类似的一种，不知道方便实现不，感谢！

**Comment by farthinker** [comment]
行间距的自定义我们是通过自定义css来实现的，毕竟在同一篇文章里一般不会有两种段间距或者行间距，如果你有特殊的排版需要可以举个例子详细说说

**Comment by hellodajun** [comment]
目前simditor的行间距是固定的回车或shift+回车，假如我从记事本或者Word粘贴一段文字到编辑器，如果要求行间距的话，需要每行逐个设置行间距，而如果有插件，选择这一段文字点击行间距就可以直接做到了。另外，查看的时候，也不用引入simditor的css样式，否则显示页面还需要引入此样式。

**Comment by farthinker** [comment]
从外面粘贴进来的内容的行间距会被自动处理，我想不通一篇文章里为什么需要设置多个行间距，如果行间距是固定的那么自定义样式就好了（我们推荐创建一个simditor-custom.css文件来专门写自定义的排版样式）
所以我暂时不会写一个这样的按钮

**Comment by hellodajun** [comment]
好的，感谢您的答复！
问题是，一篇文章的行间距只有一种，如果第二篇文章是另一种，就不好处理了。固定的行间也可以解决问题，但不是最满意的。再次感谢！
