### ISSUE TITLE
@ 后无法输入中文

### ISSUE THREAD

**Issue by huyinghuan** [mycolorway/simditor-mention#7]
重现：
运行demo示例 @ 后无法输入中文

**Comment by pcxiong** [comment]
Mac， Chrome， 搜狗，官网demo，contenteditable ，@之后中文打不出来，变成这个样子
![image](https://cloud.githubusercontent.com/assets/9209882/6166095/195eeecc-b2e8-11e4-80a5-0d00127816ee.png)
我想打“中”字。
谢谢

**Comment by syejing** [comment]
追查的结果是什么，麻烦作者说说，谢谢了

**Comment by interjc** [comment]
@RuochenLyu 目前使用 IE11 在 Win7 环境下，使用搜狗和QQ输入法，都无法触发用户选择，但是 Chrome 里面一切正常。
